### ISSUE TITLE
Line numbers do not fit when the text is scaled up

### ISSUE THREAD

**Issue by d-g** [bbatsov/solarized-emacs#240] opened 2016-07-16 19:32 UTC
Steps to reproduce:
- `M-x load-theme RET solarized-light`
- `M-x linum-mode`
- `C-x C-=`

Result:
![Result](https://i.imgur.com//kAOqCkZ.png)

There is no problem with no theme loaded, of course.

GNU Emacs 25.1.50.1 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.25), solarized-theme 20160515.442

**Comment by kshenoy** [comment] 2016-07-20 17:13
I'm seeing this too. Is it possible to specify that the face used for line numbers be of fixed width and the height used by non-section headings?

**Comment by thomasf** [comment] 2016-07-20 17:18
Hmm. I'm not seeing this.. 

I'm compiling from the emacs25 branch daily (GNU Emacs 25.0.95.28 (x86_64-unknown-linux-gnu, GTK+ Version 3.18.9) of 2016-07-19).. The main difference there seems to be gtk3, I don't know if that makes any difference for this issue. Maybe it's the difference in font settings which causes the problems, idk.

![image](https://cloud.githubusercontent.com/assets/330847/16995742/4870ed2e-4eae-11e6-9ae4-715bfdcb1dfa.png)

**Comment by thomasf** [comment] 2016-07-20 17:21
It also works for me if I set `default` and `fixed-pitch` to "Pragmata Pro-13" and `variable-pitch` to "Pt Sans-13"

**Comment by kshenoy** [comment] 2016-07-20 17:32
@thomasf I believe [these](https://github.com/kshenoy/dotfiles/blob/master/emacs.d/config.org#fonts-1) are the only customisations I'm doing to my faces.

**Comment by kshenoy** [comment] 2016-07-20 21:56
Ok, I haven't been able to root cause the issue but I think I've found a workaround for it. 

    (set-face-attribute 'fixed-pitch nil :font my-monospaced-font)
    (set-face-attribute 'linum       nil :inherit 'fixed-pitch)

This is not a solarized issue since solarized seems to be setting only the `:foreground` and `:background` attributes for `'linum`

My guess is that `'linum` grabs the attributes from the text on that line. Which may be why @d-g was seeing this only when a theme is loaded.

**Comment by thomasf** [comment] 2016-12-03 11:09
Does not seem to be a local issue, closing.

**Closed by thomasf** 2016-12-03 11:09 UTC
