### ISSUE TITLE
Incorrect Colours in Terminal

### ISSUE THREAD

**Issue by zmanji** [bbatsov/solarized-emacs#18] opened 2012-04-14 04:02 UTC
I'm not sure if this is a bug of solarized-emacs or my fault but when I load up emacs in a terminal window this is what i get:

![](http://f.cl.ly/items/3l0w0e1V1y1y1H3U0A2z/Screen%20Shot%202012-04-13%20at%2011.59.59%20PM.PNG)

However, my terminal has 256 color support and `M-x list-colors-display` displays all of the colours correctly. I don't know how to diagnose the issue further to determine where the problem lies.

**Comment by andersjohansson** [comment] 2015-01-07 18:51
@sellout has been doing some work on merging the unified-branch of the other theme (https://github.com/sellout/emacs-color-theme-solarized/) and creating tests recently (in the last 24 hours). I don't know how that relates to your work @thomasf, but I guess it could be useful to unite these efforts. I really like the "unified"-approach, and have been using this theme mostly because it supports more faces. Having the two themes merged in some way would also be quite cool.

**Comment by mikefaille** [comment] 2015-01-09 00:53
I personnaly have this problem with kmscons and tty terminal (only) using Linux.
Note : I think tty can be usefull to recover systems. (no more use case for me)

**Comment by thomasf** [comment] 2015-01-10 16:05
@andersjohansson  The version of solarized is a bit more complex because it's really an extended solarized in it's current high color only theme.

My previous attempt at doing this was unsuccessful because I was not satisfied with the preciseness of the code when doing it with the basic emacs lisp code.

Next time I will use pattern matching to build the facedefs. The target is to only depend on dash.el. I was actually holding off this work while waiting for dash.el to get support for plists which it now has!

**Comment by mikefaille** [comment] 2015-01-10 19:28
@thomasf I personnaly pass a lot of time to find.. Why Wombat OEM  work always with load theme  ? ! 
Emacs OEM theme set is only theme who always work using : kmscons --palette solarized
or just kmscons (without palette)
It's cool because... Wombat is really simple : http://git.savannah.gnu.org/cgit/emacs.git/tree/etc/themes/wombat-theme.el?h=emacs-24

Why emacs theme can be complicated ? It's because color interpolation between desired and current env. palette limitation.
If I understand by experience, emacs seems to interpolate colors very well by default. 
I think this is documented too (english isn't my 1st language and I try to don't use Google translate to pratice..) : https://www.gnu.org/software/emacs/manual/html_node/efaq/Colors-on-a-TTY.html

My suggestion : 
Make simple solarized theme using no color interpolation.

**Comment by thomasf** [comment] 2015-01-11 17:43
First, wombat is a simple theme just defining the basic faces of emacs. This solarized theme also defines specific faces for many many more modes, without looking I would guess that solarized has more than 10 times as much definitions.

I'm not sure which interpolation you are referring to exactly but there are several kinds of mappings that has to be done in the theme to support things like the terminal solarized palette https://github.com/altercation/solarized#the-values
 . especially for 8 and 16 color modes.

Theres always the other solarized theme for people who wants something else: https://github.com/sellout/emacs-color-theme-solarized/

**Comment by mikefaille** [comment] 2015-01-11 20:03
_First, wombat is a simple theme just defining the basic faces of emacs. _
I know. But, for "simple" theme, I talk only about main color correctness. --> I want modes color adjustment.

Interpolation = choosing most correct way to provide correctness with constraint. Like drawing an diagonal line with pixel. So, interpolation for me is mapping for you. I'll use mapping in future.

Tomasf, I tested solaried only on 256 color terminal. Just to be sure, kmscons tty can use 256 color at time but dynamically (the palette is dynamic depending what color you ask ). And, emacs OEM theme always work under all condition. (I talk about base color only like background for example)

**Comment by thomasf** [comment] 2015-01-11 20:44
The problem with a regular 256 color display is that it cannot display the correct solarized colors, so the specified 16color palette which has to be configured in the terminal client is preferable to an 256color term. This is one instance where the theme starts to depend on user terminal configuration.

This theme also does some color blending to produce color ranges for cases like vc-annotate and other.. I was not sure if you were referring to that as interpolation.. Now I understand.  Mapping would probably be the correct term for what we are talking about (it cannot be interpolated). 

The background color is actually specified as #002b36. IIRC, emacs own interpolation/mapping is what is seen in the image at the top of this issue.  This happens if TERM is one of the supported 256color terminals that emacs supports.

 In the mapping table  #002b36  should respond to #1c1c1c in 256 color mode or color #8 in 16 color mode (if solarized is correctly configured for the terminal). 

I have oth

**Comment by thomasf** [comment] 2015-01-11 21:31
@mikefaille   Trying to answer your initial query:

The reason why this is a non issue for the wombat theme is that it does not have to adapt to an extended set of environmental (color mode) properties. 

If this is to be  maintainable (in this theme) the facedefs have to be build using some kind of composition while keeping the option to add exceptions for indivudual facedefs so that the lowest color modes can be constructed properly..

The sellout theme has about 100 lines of code to support the "easier" non extended solarized which kind of starts here: 

https://github.com/sellout/emacs-color-theme-solarized/blob/master/solarized-definitions.el#L93

**Comment by mikefaille** [comment] 2015-01-11 21:59
Wow, thank you for your complete answer ! I'll try to help soon. (~1 week)

**Comment by localredhead** [comment] 2015-02-12 19:39
I gave up on solarized.... Just use ```zenburn``` as it just works and looks great in the terminal.

**Comment by mikefaille** [comment] 2015-02-12 19:42
I tried and i'm not sure I have time to resolve this bug...

**Comment by andschwa** [comment] 2015-02-12 20:16
@localredhead I do both!

``` elisp
;; theme (wombat in terminal, solarized otherwise)
(use-package solarized
  :if (display-graphic-p)
  :load-path ,(f-expand "site-lisp/solarized-emacs" user-emacs-directory)
  :config
  (progn
    (setq solarized-use-variable-pitch nil
	  solarized-scale-org-headlines nil)
    (load-theme 'solarized-dark t)))

(use-package zenburn-theme
  :if (not (display-graphic-p))
  :init (load-theme 'zenburn))
```

**Comment by thomasf** [comment] 2015-04-12 17:16
This is what I do in init.el. I find anti zenburn to be a good choice for 256color light terminals. It's close to what @andschwa is doing.


```elisp

(defvar theme-bright nil "A light theme.")
(defvar theme-dark nil "A dark theme.")

(use-package solarized-theme
  :ensure t
  :if window-system
  :init
  (progn
    (setq solarized-use-less-bold t
          solarized-use-more-italic t
          solarized-emphasize-indicators nil
          solarized-distinct-fringe-background nil
          solarized-high-contrast-mode-line nil))
  :config
  (progn
    (load "solarized-theme-autoloads" nil t)
    (setq theme-dark 'solarized-dark
          theme-bright 'solarized-light)))

(use-package zenburn-theme
  :ensure t
  :if (not window-system)
  :config
  (progn
    (use-package anti-zenburn-theme
      :ensure t
      :config
      (load "anti-zenburn-theme-autoloads" nil t))
    (load "zenburn-theme-autoloads" nil t)
    (setq theme-dark 'zenburn
          theme-bright 'anti-zenburn)))

(defun post-change-theme ()
  (set-face-inverse-video-p 'vertical-border nil)
  (set-face-background 'vertical-border (face-background 'default)))

(eval
 '(set-display-table-slot standard-display-table
                          'vertical-border
                          (make-glyph-code ?┃)))

(defun dark-theme ()
  "Switch to dark mode (dark color theme)."
  (interactive)
  (when theme-dark
    (load-theme theme-dark t)
    (setq dark-theme-on t)
    (post-change-theme)))

(defun bright-theme ()
  "Switch to light mode (light color theme)."
  (interactive)
  (when theme-bright
    (load-theme theme-bright t)
    (setq dark-theme-on nil)
    (post-change-theme)))

(defun toggle-dark-theme ()
  "Toggle between light and dark modes."
  (interactive)
  (if (bound-and-true-p dark-theme-on)
      (bright-theme)
    (dark-theme))
  (post-change-theme))

(and (not (boundp 'dark-theme-on))
   (not noninteractive)
   (bright-theme))

```

**Comment by andschwa** [comment] 2015-04-14 03:43
@thomasf I like your toggle! Totally going to borrow it :smile:

**Comment by thomasf** [comment] 2015-04-14 09:53
It's not very pretty but it works.. I have a macro that precompiles the load path so that I do not have to  require package.el at load time so thats why the (load "solarized-theme-autoloads" nil t) are there since they modify the theme paths which is not in my load-path macro (right now).

**Comment by jarandaf** [comment] 2015-04-14 20:49
+1, using solarized preset within iTerm2 for the time being

**Comment by ephexeve** [comment] 2015-07-14 19:54
I still have this issue. Has anyone figured out how to fix this?

**Comment by bassu** [comment] 2015-07-14 20:34
People, please stop complaining because at this point, we literally want you to switch to the GUI :smiling_imp:

**Comment by ephexeve** [comment] 2015-07-14 20:36
@bassu, not willing to be rude, but I you should the question better =]. I never complained. Just asked if anyone managed to fix it.
I am using the GUI. Just curious to know about Term :).

Cheers!

**Comment by ephexeve** [comment] 2015-07-14 20:37
Oh and btw, the work you guys are doing is great.

**Comment by mikefaille** [comment] 2015-07-14 20:37
Personnally, I use the gui, but my shell work better than tramp sometimes under remote conditions.

**Comment by bassu** [comment] 2015-07-14 20:39
@ephexeve Yeah, I just being cynical, LOL. For the easiest and simplest workaround: see my last year's comment in this very bug report. Make sure to set solarized dark theme in whatever terminal you are using.

**Comment by ephexeve** [comment] 2015-07-14 20:41
@bbatsov Will do that, I barely use Emacs on the Terminal anyway, but when I use it, I will just work with the ugly blue theme :p. Like they say, YOLO.

**Comment by bassu** [comment] 2015-07-14 20:44
@ephexeve LOL, okay. The workaround is pretty is just one line though. But you replied to @bbatsov, and I think he'll not be happy to find this bug's email the very first thing he sees when he wakes up this morning. Haha. :beers:

**Comment by PythonNut** [comment] 2015-09-14 15:58
An alternative solution that may interest y'all is implementing [24 bit terminal colors](https://gist.github.com/XVilka/8346728) in Emacs. It's already supported in most of the major terminals. 

Sadly, I don't know enough C and Emacs guts to implement this myself. I know there were some patches flying around that added it, but I think the person working on them went MIA.

**Comment by seanstrom** [comment] 2015-11-19 19:40
@PythonNut [Here's](http://hoppsjots.org/?p=133) an article that lists the patches that exist for adding 24 bit color support to emacs 24.3 and 24.4. There's also a more recent patch for emacs 24.5 [here](https://gist.github.com/choppsv1/e8198df70cb1778b04d6).

**Comment by chumakd** [comment] 2016-02-09 10:29
as a workaround for iTerm2 with solarized palette and tmux with 256 colors I use this trick in my `.bashrc`, which makes emacs think it's running on a 16 color terminal and use correct solarized colors:

`alias emacs='TERM=screen-16color emacs -nw'`

**Comment by RafalLukawiecki** [comment] 2017-03-12 21:21
For what it is worth, I am using GNU emacs 25.1.1 and I am affected by this issue in iTerm2 on OS X 10.12. I have scanned through this thread, but I cannot see what is the recommended fix. The https://github.com/sellout/emacs-color-theme-solarized theme does not have this issue, but it has other ones that I am hoping to avoid by using this one.

Should I open a new issue about this? Or is there is a fix? Many thanks indeed and my regards from Ireland.

**Comment by Alexander-Shukaev** [comment] 2017-03-12 22:09
Looking for the fix as well...

**Comment by srustamo** [comment] 2017-04-20 06:02
> this version of emacs requires a custom terminfo description xterm-24bit, which needs to be compiled manually

@krksgbr can you please elaborate how to compile manually?

**Comment by krksgbr** [comment] 2017-04-21 07:09
@srustamo I've edited my comment to make the steps more clear.

**Comment by srustamo** [comment] 2017-04-21 07:22
@krksgbr 

Let me know if I understand correctly:

1. Need to use emacs-plus (nothing else needs to be config'ed on emacs side)
2. Need to compile terminfo with `tic -x -o ~/.terminfo terminfo-24bit.src`

`tic` man says "The results are normally placed in the system terminfo directory /usr/share/terminfo." 

Is this correct?

**Comment by krksgbr** [comment] 2017-04-21 07:40
@srustamo 
yeah that's correct. the only thing is that contrary to what the tic manual says, it will always output the results to ~/.terminfo even when run as root, so I just added that to the command to make it explicit.

**Comment by s-kostyaev** [comment] 2017-07-06 21:17
I use this workaround for emacs & emacsclient:
```
(defun my-solarized-dark-workaround (frame)
  "Fix solarized-dark theme for terminal FRAME."
  (with-selected-frame frame
    (if (and (featurep 'color-theme)
             (not window-system))
        (set-face-background 'default "none" frame))))

(add-hook 'after-make-frame-functions #'my-solarized-dark-workaround)
```
I also add `(seq-doseq (frame (frame-list)) (my-solarized-dark-workaround frame))` to `my-set-themes`.

**Comment by srustamo** [comment] 2017-07-08 10:17
What is 'my-set-themes' variable and where do you define it?

**Comment by s-kostyaev** [comment] 2017-07-08 11:50
`my-set-themes` it's function for `after-init-hook` and some other hooks. For example it executes after update and reload updated packages.

**Comment by chuan-su** [comment] 2017-10-02 21:12
really looking forward to have this fixed. +1

**Comment by bhamiltoncx** [comment] 2018-01-22 16:59
This is still broken. :/

**Comment by mikefaille** [comment] 2018-01-23 00:56
­> If users change that setting, I assume the colors will be correct for Terminal, but incorrect for the Emacs GUI, right?
@bhamiltoncx  For current et futur users, it shouldn't change anything if solarized-termcolors isn't set. For others, this hack should be consider not as a solution by itself but like a helper to enable terminal detection like end "user" want.

**Comment by NightMachinary** [comment] 2018-03-07 10:10
@mikefaille The fix doesn't work for me. Black background on the light theme.

**Comment by deybhayden** [comment] 2018-03-23 04:11
@krksgbr Is right on - the 24-bit color bit made this theme work perfectly in the terminal.

**Comment by NightMachinary** [comment] 2018-03-23 22:12
@deybhayden Indeed! Thanks!
BTW I needed to use this code for it to work with iTerm2:
```
# Use colon separators.
xterm-24bit|xterm with 24-bit direct color mode,
   use=xterm-256color,
   setb24=\E[48:2:%p1%{65536}%/%d:%p1%{256}%/%{255}%&%d:%p1%{255}%&%dm,
   setf24=\E[38:2:%p1%{65536}%/%d:%p1%{256}%/%{255}%&%d:%p1%{255}%&%dm,
# Use semicolon separators.
xterm-24bits|xterm with 24-bit direct color mode,
   use=xterm-256color,
   setb24=\E[48;2;%p1%{65536}%/%d;%p1%{256}%/%{255}%&%d;%p1%{255}%&%dm,
   setf24=\E[38;2;%p1%{65536}%/%d;%p1%{256}%/%{255}%&%d;%p1%{255}%&%dm,
```

**Comment by srustamo** [comment] 2018-09-04 10:11
> compile the terminfo source: tic -x -o ~/.terminfo terminfo-24bit.src

@krksgbr you are not on OSX by any chance? After compiling the terminfo without errors as quoted above, running ``` TERM=xterm-24bits emacs -nw``` gives me this error:

```
zsh: can't find terminal definition for xterm-24bits
emacs: Cannot open terminfo database file
```

Looks like ~/.terminfo is ignored. Any ideas?

**Comment by srustamo** [comment] 2018-09-04 10:16
@NightMachinary How did you install the terminfo [here](https://github.com/bbatsov/solarized-emacs/issues/18#issuecomment-375811954)?

**Comment by NightMachinary** [comment] 2018-09-04 17:05
I don’t remember, google it, there was an StackExchange question I think.

**Comment by YujiShen** [comment] 2018-10-04 19:55
@srustamo I encounter the same problem and I found a solution.

For all folks have error when set `TERM` variable on Mac, use system `tic` instead of `tic` you installed (maybe from `conda` or whatever), for example:

```
/usr/bin/tic  -x -o ~/.terminfo  terminfo-24bit.src
```

**Comment by srustamo** [comment] 2018-10-08 08:49
@YujiShen brilliant!

**Comment by martinweiss** [comment] 2018-11-14 12:37
I am using terminal Emacs 25.1.1 on a Raspberry Pi Zero W running Raspbian Stretch. When I set the theme so solarized-dark, I get a blue screen.

I have tried what @krksgbr suggested, and I have also tried to run Emacs using
`$TERM=xterm-256color emacs`

However, that gives me the same result. Any ideas?

**Comment by srustamo** [comment] 2018-11-14 13:10
@martinweiss I think you need an Emacs w 24bit support. The earliest
supported v is 26, afaik.

**Comment by martinweiss** [comment] 2018-11-14 14:03
Thanks for your reply. However, all colour schemes look wrong as far as I can see, so I'm not really sure what to do. 

Do one of the other solarized packages work?

**Comment by srustamo** [comment] 2018-11-14 14:19
You also need a terminal with 24bit support. If all colors are off, it is
clearly a terminal issue.

**Comment by martinweiss** [comment] 2018-11-15 11:40
Hmm. But does that mean it's not possible to get correct colors without 24-bit Emacs and terminal?

**Comment by NightMachinary** [comment] 2018-11-15 11:52
This is the conclusion we have come to on this thread😂🔫 The default theme
works fine with a 256-colors terminal though.

**Comment by martinweiss** [comment] 2018-11-15 12:03
The screenshot in the first post is for Emacs running on macOS. I wasn't sure if it would be the same in Raspbian (sorry for asking I guess).

It seems like Zenburn works OK too, so I'll use that on the machines that don't have GUI Emacs.

**Comment by luluman** [comment] 2019-01-04 08:42
I have tried [emacs-color-theme-solarized](https://github.com/sellout/emacs-color-theme-solarized), and it works fine in terminal. But I prefer solarized-emacs better because solarized-emacs is more active and have fine tuning for other modes. But the time comes to 2019, and I hope this issue can be fixed.  I work on the terminal and need this feature very much. Thanks.

**Comment by kilowu** [comment] 2019-01-04 14:52
There is an on-going pull request #283 addressing this issue. The fix is using the same approach as [emacs-color-theme-solarized](https://github.com/sellout/emacs-color-theme-solarized) does. It requires you pre-set a terminal with the solarized 16-color palette which is already builtin included in gnome-terminal and iterm2.

**Comment by luluman** [comment] 2019-01-04 15:04
Ok, I will try. Thanks, @kilowu.

**Comment by jimmysjolund** [comment] 2019-08-30 22:08
I got this problem in my urxvt terminal. I solved it by changing:

(s-base03 "#002b36")

to #1c1c1c in the solarized.el.

I suppose at least for my terminal I should use the Xterm hex values:
SOLARIZED HEX     16/8 TERMCOL  XTERM/HEX   L*A*B      RGB         HSB
--------- ------- ---- -------  ----------- ---------- ----------- -----------
base03    #002b36  8/4 brblack  234 #1c1c1c 15 -12 -12   0  43  54 193 100  21

**Comment by RafalLukawiecki** [comment] 2020-02-07 18:44
The [workaround mentioned above](https://github.com/bbatsov/solarized-emacs/issues/18#issuecomment-375811954) of creating a terminfo xterm-24bit works nicely in Emacs 26.3 with and without tmux. Thank you! However, I now have a new problem: anything that uses the "less" pager, like git, man etc, now complains with "WARNING: terminal is not fully functional".

I am using iTerm 3.3.8 on macOS 10.14.6 and zsh. Many thanks for any pointers, anyone.

**Comment by RafalLukawiecki** [comment] 2020-02-09 15:47
For what it is worth, there is a further workaround for those who use this theme on FreeBSD in a remote shell session. It involves recompiling ncurses with `--disable-termcap` and then recompiling emacs to make use of that—[see this StackExchange post](https://unix.stackexchange.com/questions/512845/emacs-with-24bit-terminal-support-on-freebsd/566609#566609). It works, but it is all much too much of a workaround—it would be better to have the theme fixed.

**Comment by andschwa** [comment] 2020-12-24 20:42
This is bizzare. So I’m using Emacs on an Ubuntu 20.04 instance over SSH with the [Blink](https://blink.sh) iPad app...and surprisingly I’ve gotten this to work. I followed the instructions in the latest Emacs FAQ (after building Emacs from the 27.1 source branch) [Colors on a TTY](https://www.gnu.org/software/emacs/manual/html_node/efaq/Colors-on-a-TTY.html), which several comments above mention and reproduce in its various versions.

But I had to change the `\:` (backslash colons) in the `xterm-emacs` entry to just `;` (semicolons) to make things work (I also joined the lines to get rid of the backslash-newline but I don’t think that’s it). That’s it, that’s the only change. With the documented entry, `tic` compiles fine but then Emacs has no colors. Replace the custom entry with semicolons instead and Emacs suddenly works with full 24 bit color support (and the Solarized background is correct).

The original commit https://github.com/emacs-mirror/emacs/commit/e463e5762bbe628be3d15da066a90f079a8468b3 to the FAQ referenced this “use colons” and “use semicolons” entries like in the above comments, but then it was removed without documented reason in https://github.com/emacs-mirror/emacs/commit/7f6153d9563cfe7753083996f59eacc9f4c694df. I only a little bit about termcap/terminfo; can anyone here shed light on why I needed to use semicolons instead of backslash-colons, and does it hint at something deeper?

For reference, I did this:
```
$ cat terminfo-custom.src 
# See Emacs FAQ "Colors on a TTY" but sub ; for ;
xterm-emacs|xterm with 24-bit direct color mode for Emacs,
  use=xterm-256color,
  setb24=\E[48;2;%p1%{65536}%/%d;%p1%{256}%/%{255}%&%d;%p1%{255}%&%dm,
  setf24=\E[38;2;%p1%{65536}%/%d;%p1%{256}%/%{255}%&%d;%p1%{255}%&%dm,
$ tic -x -o ~/.terminfo terminfo-custom.src
$ TERM=xterm-emacs emacs
```

**Comment by done-with-fish** [comment] 2021-07-07 17:42
This is still an issue for me (arch linux with st+solarized patch). Has anyone managed to cobble together a solution?

**Comment by analyticd** [comment] 2021-07-22 03:27
On macOS with alacritty terminal and emacs -nw you can get true color both within tmux and without tmux. Never did get 24bit in iTerm2 though with emacs.

**Comment by thomasf** [comment] 2021-07-24 06:19
Yeah I have got it working in Alacritty under Linux, MacOS and IIIRC Windows as well and other terminals. You might have to fiddle around with termcap files though.

**Comment by thomasf** [comment] 2021-07-24 06:24
This is likely never going to be "fixed" for anything below true color. We use too many non standard solarized colors so we can't fit it all into 16 colors even if we tried and it's a huge job mapping and maintaining all those colors into something that actually displays properly on low color displays. It's probably just not worth it. 

At this point more and more terminals are getting 24bit color support and I think only focusing on that and non GUI toolkit environments is the right choice for this theme.

**Closed** 2021-07-24 06:55 UTC
Labels: bug (non facedefs), undecided

**Comment by done-with-fish** [comment] 2023-08-04 17:34
This issue has plagued me forever. I used to get around it by changing `base03` to `#7f7f7f` and `base02` to `#000000`.

However, to my pleasant surprise, the colors started to work after upgrading to emacs 29.1! Thought I'd post here in case anyone else has had this issue as long as I have!
